### ISSUE TITLE
Getting error when I run 'azk shell deploy' command

### ISSUE THREAD

**Issue by vitormateus** [azukiapp/docker-deploy#1]
`/azk/deploy/deploy.sh: 3: /azk/deploy/deploy-run: cannot create playbooks/roles/configure/files/authorized_keys: Directory nonexistent`

**Comment by fearenales** [comment]
Thanks for your report @vitormateus ! When I pushed files to Github, the path `playbooks/roles/configure/files` (an empty dir originally) was left behind...

I'm fixing it right now and as soon as it get fixed be sure I'll ping you back!

**Comment by fearenales** [comment]
@vitormateus It's fixed. Would you mind to check if it worked for you?

**Comment by vitormateus** [comment]
@fearenales works nice!
thanks!
