### ISSUE TITLE
After initial azk deploy, subsequent deploys ask for password from git

### ISSUE THREAD

**Issue by patrickleet** [azukiapp/docker-deploy#18]
``` shell
➜  elite git:(master) azk deploy
git@111.111.11.111's password:
```

From googling around it looks like the remote server needs access to git, which is a private repository.

Seems like it could be something like using SSH Agent Forwarding? https://developer.github.com/guides/using-ssh-agent-forwarding/

**Comment by fearenales** [comment]
@patrickleet are you deploying to a DigitalOcean droplet or for some other box?

**Comment by patrickleet** [comment]
@fearenales it's a digital ocean droplet

**Comment by patrickleet** [comment]
```
deploy: {
    image: {"docker": "azukiapp/deploy-digitalocean"},
    mounts: {
      "/azk/deploy/src" :    path("."),
      "/azk/deploy/.ssh":    path("#{env.HOME}/.ssh"),
      "/azk/deploy/.config": persistent("deploy-config"),
    },
    scalable: {"default": 0, "limit": 0},
  }
```

**Comment by fearenales** [comment]
OK, and you have properly configured SSH keys at `~/.ssh`, right?

**Comment by patrickleet** [comment]
yes - I deleted the deployment, and am trying again now

**Comment by patrickleet** [comment]
This seems to have been caused by having my application in a sub directory of the git repository.

./repo/app/ 

I moved everything to the root, and am no longer getting this error.

**Comment by fearenales** [comment]
@patrickleet that's odd... But thank you for your feedback,  I'll investigate it further.

**Comment by patrickleet** [comment]
Could have been a fluke, I'm in trying to deploy to a US server from South Africa and my internet is quite slow :/

**Comment by bartekus** [comment]
The easiest way to fix that as far as I could tell was to do:

> azk deploy clear-cache

after that:

> azk deploy
