### ISSUE TITLE
Deploy my simple rails project into AWS

### ISSUE THREAD

**Issue by vitormateus** [azukiapp/docker-deploy#2]
I trying to deploy my simple rails project into AWS. But I need some help.

I just create a EC2 machine with Ubuntu and config my ssh access.  When I run azk shell deploy, I receive that info:
https://gist.github.com/vitormateus/66259c3ee8ed4af2d0b2

First question: What am I doing wrong?
Second question: How do I access the final url?

**Comment by fearenales** [comment]
What's in your `git remote -v`?

**Comment by vitormateus** [comment]
@fearenales I'm using heroku too

`➜  landing git:(develop) ✗ git remote -v`
`azk_deploy ssh://git@52.3.5.161:22/home/git/d00d71b.git (fetch)`
`azk_deploy ssh://git@52.3.5.161:22/home/git/d00d71b.git (push)`
`heroku https://git.heroku.com/landing-page.git (fetch)`
`heroku https://git.heroku.com/landing-page.git (push)`
`origin git@bitbucket.org:buzz/landing-page.git (fetch)`
`origin git@bitbucket.org:buzz/landing-page.git (push)`

**Comment by vitormateus** [comment]
@fearenales, are you working on something?

I test without heroku remote and I got another error:
https://gist.github.com/vitormateus/0ce837dff87dc5b98453

**Comment by fearenales** [comment]
What happens if you run `git push -f azk_deploy`?

**Comment by vitormateus** [comment]
`landing git:(develop) git push -f azk_deploy`
`Everything up-to-date`

**Comment by vitormateus** [comment]
@fearenales if you need my Azkfile.json
https://gist.github.com/vitormateus/fbc0db986a06327bccf9

**Comment by fearenales** [comment]
That's quite odd @vitormateus ...
When you use this image, an ansible playbook sets the remote server up.
Among other things, it creates a bare git repository (`/home/git/d00d71b.git` in your case) which stores git objects.
When you run a push, it checks your source code out into /home/git/d00d71b and runs `azk restart`.

If you can run an SSH into that box and check if the repo exists and if the source code is that would be great!
Plus, ansible creates a `git` user. Please, check if it exists in fact and if those folders are properly assigned to him.

BTW, thank you for your support!

**Comment by vitormateus** [comment]
@fearenales right. I just check that. I see folders (like you mention) and my source files. Now when I run 'azk restart' into AWS machine with git user I receive that error:
https://gist.github.com/vitormateus/c40bbf71b62439a125e2

I'm really impress with Azk, it's a great tool for us (develops and devops).

Thk you for a really great job ;)

**Comment by fearenales** [comment]
Thank you for your compliment, @vitormateus ! I really appreciate. :)

In the server box, what's the installed docker version?
