### ISSUE TITLE
Post receive command should be customizable for a specific deploy

### ISSUE THREAD

**Issue by fearenales** [azukiapp/docker-deploy#8]
The issue https://github.com/azukiapp/docker-deploy/issues/3 demanded that the post receive command should be customizable.

However, it's still the same for all deploys since it's set in setup time, not runtime.

We should be able to run something like:

```
$ azk shell deploy -e AZK_RESTART_COMMAND="azk restart -R -vvvv --rebuild"
```

modifying the post receive command for that specific deploy.

**Comment by gullitmiranda** [comment]
One option would be to use ENV instead of templates in the [post-receive](https://github.com/azukiapp/docker-deploy/blob/master/latest/playbooks/roles/configure/templates/post-receive.j2#L10-L16) file.

``` shell
echo "$> ${AZK_AGENT_START_COMMAND}"
eval ${AZK_AGENT_START_COMMAND}

echo ""; echo "Starting azk. Maybe downloading images be needed. Please be patient."

echo "$> ${AZK_RESTART_COMMAND}"
eval ${AZK_RESTART_COMMAND}
```
